/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cineslave.gui;

import com.cineslave.controlador.Gestor_Compras;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Erikthegod
 */
public class JPanelCompra extends javax.swing.JPanel {

    private JFPrincipal jfe;
    private Gestor_Compras gest;
    private Connection con;
    private ArrayList<String> nombrePeliculas;
    private ArrayList<String> sesionesDisponibles;
    private ArrayList filasDisponibles;
    private ArrayList columnasDisponibles;
    String nombrePeli;
    int numFila;
    String horaSesion;
    int numColumna;

    JPanelCompra(JFPrincipal aThis, Connection conTotal) {
        try {
            initComponents();
            this.jfe = aThis;
            this.con = conTotal;
            gest = new Gestor_Compras(con);
            nombrePeliculas = gest.recuperarPeliculas();
            for (int i = 0; i < nombrePeliculas.size(); i++) {
                jcbPeliculas.addItem(nombrePeliculas.get(i));
            }
        } catch (Exception ex) {
            Logger.getLogger(JPanelCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbCompra = new javax.swing.JButton();
        jcbPeliculas = new javax.swing.JComboBox<>();
        jcbSesion = new javax.swing.JComboBox<>();
        jcbFila = new javax.swing.JComboBox<>();
        jcbColumna = new javax.swing.JComboBox<>();
        jbMostrar = new javax.swing.JButton();

        jLabel1.setText("Pelicula");

        jLabel2.setText("Cliente");

        jLabel3.setText("Sesion");

        jLabel4.setText("Fila");

        jLabel5.setText("Columna");

        jbCompra.setText("Generar Compra");
        jbCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCompraActionPerformed(evt);
            }
        });

        jcbPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPeliculasActionPerformed(evt);
            }
        });

        jcbSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSesionActionPerformed(evt);
            }
        });

        jcbFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFilaActionPerformed(evt);
            }
        });

        jbMostrar.setText("Mostrar Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbPeliculas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jcbSesion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbFila, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbColumna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jbCompra))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jbMostrar)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCompraActionPerformed
        try {
            nombrePeli = jcbPeliculas.getSelectedItem().toString();
            horaSesion = jcbSesion.getSelectedItem().toString();
            String nombreCli = jtfCliente.getText();
            numFila = Integer.parseInt(jcbFila.getSelectedItem().toString());
            numColumna = Integer.parseInt(jcbFila.getSelectedItem().toString());
            gest.generarCompra(nombrePeli, horaSesion, nombreCli, numFila, numColumna);
            JOptionPane.showMessageDialog(null, "Compra generada");
        } catch (SQLException ex) {
            Logger.getLogger(JPanelCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCompraActionPerformed

    private void jcbPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPeliculasActionPerformed
        try {
            sesionesDisponibles = new ArrayList();
            jcbSesion.removeAllItems();
            nombrePeli = jcbPeliculas.getSelectedItem().toString();
            sesionesDisponibles = gest.recuperarSesiones(nombrePeli);
            for (int i = 0; i < sesionesDisponibles.size(); i++) {
                jcbSesion.addItem(sesionesDisponibles.get(i));

            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelCompra.class
                    .getName()).log(Level.SEVERE, null, ex);}    }//GEN-LAST:event_jcbPeliculasActionPerformed

    private void jcbSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSesionActionPerformed
        try {
            filasDisponibles = new ArrayList();
            jcbFila.removeAllItems();
            horaSesion = jcbSesion.getSelectedItem().toString();
            filasDisponibles = gest.recuperarFilas(nombrePeli, horaSesion);
            for (int i = 0; i < filasDisponibles.size(); i++) {
                jcbFila.addItem(filasDisponibles.get(i).toString());

            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelCompra.class
                    .getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_jcbSesionActionPerformed

    private void jcbFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFilaActionPerformed
        try {
            columnasDisponibles = new ArrayList();
            jcbColumna.removeAll();
            numFila = Integer.parseInt(jcbFila.getSelectedItem().toString());
            columnasDisponibles = gest.recuperarColumnas(numFila, horaSesion);
            for (int i = 0; i < columnasDisponibles.size(); i++) {
                jcbColumna.addItem(columnasDisponibles.get(i).toString());

            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelCompra.class
                    .getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_jcbFilaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCompra;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JComboBox<String> jcbColumna;
    private javax.swing.JComboBox<String> jcbFila;
    private javax.swing.JComboBox<String> jcbPeliculas;
    private javax.swing.JComboBox<String> jcbSesion;
    private javax.swing.JTextField jtfCliente;
    // End of variables declaration//GEN-END:variables
}
