/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cineslave.gui;

import com.cineslave.controlador.Gestor_Pedidos;
import com.cineslave.controlador.Gestor_Pelicula;
import com.cineslave.controlador.Gestor_Productos;
import com.cineslave.modelo.Pelicula;
import com.cineslave.modelo.Producto;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author juanxxiii
 */
public class JPanelProducto extends javax.swing.JPanel {

    private JFPrincipal jfe;
    Connection con;

    Gestor_Productos gProd;
    ArrayList alProductos;
    int precio = 0;

    /**
     * Creates new form JPanelProducto
     */
    public JPanelProducto(JFPrincipal jfe, Connection con) {
        initComponents();
        this.jfe = jfe;
        this.con = con;
        jcbProductos.removeAllItems();
        gProd = new Gestor_Productos(con);
        alProductos = new ArrayList();

        try {
            alProductos = gProd.consultarProductos();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < alProductos.size(); i++) {
            jcbProductos.addItem((String) alProductos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombreProducto = new javax.swing.JTextField();
        jtfPrecioProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbAddProducto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbModificarProducto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfPrecioProductoConsulta = new javax.swing.JTextField();
        jcbProductos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jbBorrarProducto = new javax.swing.JButton();
        jbConsultarProducto = new javax.swing.JButton();
        jtfDescrioción = new javax.swing.JTextField();

        jLabel2.setText("Descripción");

        jLabel3.setText("Precio");

        jbAddProducto.setText("Crear");
        jbAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("AÑADE UN NUEVO PRODUCTO");

        jLabel4.setText("Descripción");

        jLabel5.setText("Precio");

        jbModificarProducto.setText("Modificar");
        jbModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarProductoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("CONSULTAS Y MODIFICACIONES");

        jcbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbProductos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbProductosFocusGained(evt);
            }
        });

        jLabel7.setText("Elige un Producto");

        jbBorrarProducto.setText("Eliminar");
        jbBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarProductoActionPerformed(evt);
            }
        });

        jbConsultarProducto.setText("Consultar");
        jbConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jtfNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(jtfPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jbAddProducto))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jcbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jtfDescrioción, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(jtfPrecioProductoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jbConsultarProducto)
                .addGap(40, 40, 40)
                .addComponent(jbBorrarProducto)
                .addGap(55, 55, 55)
                .addComponent(jbModificarProducto))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jbAddProducto)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(jcbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jtfDescrioción, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(jtfPrecioProductoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbConsultarProducto)
                    .addComponent(jbBorrarProducto)
                    .addComponent(jbModificarProducto)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProductoActionPerformed
        Producto prod = new Producto(jtfNombreProducto.getText().toLowerCase(),
                Integer.parseInt(jtfPrecioProducto.getText()));

        try {
            gProd.crearProducto(prod);
            System.out.println("Se ha creado su producto");
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAddProductoActionPerformed

    private void jbConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarProductoActionPerformed
        try {
            String descProd = (String) jcbProductos.getSelectedItem();
            precio = gProd.consultarPrecio(descProd);
            jtfDescrioción.setText(descProd);
            jtfPrecioProductoConsulta.setText(String.valueOf(precio));
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultarProductoActionPerformed

    private void jbBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarProductoActionPerformed
        try {
            String descProd = (String) jcbProductos.getSelectedItem();
            gProd.borrarProducto(descProd);
            jtfDescrioción.setText("");
            jtfPrecioProductoConsulta.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBorrarProductoActionPerformed

    private void jcbProductosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbProductosFocusGained
        jcbProductos.removeAllItems();
        try {
            alProductos = gProd.consultarProductos();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < alProductos.size(); i++) {
            jcbProductos.addItem((String) alProductos.get(i));
        }
    }//GEN-LAST:event_jcbProductosFocusGained

    private void jbModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarProductoActionPerformed
        try {
            Producto prod = new Producto(jtfDescrioción.getText(), Integer.parseInt(jtfPrecioProductoConsulta.getText()));
            String descProd = (String) jcbProductos.getSelectedItem();
            gProd.modificarProducto(prod, descProd);

        } catch (SQLException ex) {
            Logger.getLogger(JPanelProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAddProducto;
    private javax.swing.JButton jbBorrarProducto;
    private javax.swing.JButton jbConsultarProducto;
    private javax.swing.JButton jbModificarProducto;
    private javax.swing.JComboBox<String> jcbProductos;
    private javax.swing.JTextField jtfDescrioción;
    private javax.swing.JTextField jtfNombreProducto;
    private javax.swing.JTextField jtfPrecioProducto;
    private javax.swing.JTextField jtfPrecioProductoConsulta;
    // End of variables declaration//GEN-END:variables
}
